version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=db
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
  db:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
