services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml

  database:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
