services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=database
    depends_on:
      - database

  database:
    image: mongo:7-jammy
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
